### ISSUE TITLE
No HDMI ouput, cannot log in via ssh

### ISSUE THREAD

**Issue by citroboy** [manjaro-arm/station-p2-images#3]
I tried the 20220822 image on my P2. I have the OS Bootloader enabled on the latest Station OS. The power light blinks on-on-off a few times then stays off. There is no output on the HDMI. It does boot as I can see ssh and smb on the network but I can't log in with the usual credentials.

**Comment by Strit** [comment]
What usual credentials?
Unless you finished the setup, there are no credentials.

Setup via SSH only works on minimal edition. You can do it by connecting as `root` and without a password.
